### ISSUE TITLE
Overriding php.ini settings doesn’t seem to work

### ISSUE THREAD

**Issue by stiang** [cytopia/docker-php-fpm-5.4#26]
I’m not able to override any php.ini settings, but I don’t understand why.

I’ve mounted a local directory with a single override file at `/etc/php-custom.d` (in the docker image), I have confirmed that the file is present and readable inside the container by ssh-ing in, I have confirmed that the custom ini file should be read (by using `php --ini` and `phpinfo()`, but none of my overrides are respected. Here is the contents of my override file:

```
[PHP]
error_reporting = E_ERROR
display_errors = Off
``` 

But notices are still printed to the screen when I load a PHP script that triggers a Notice.

Do you have any ideas why this won’t work?

**Comment by cytopia** [comment]
How are you using this docker container. It could be possible that the webserver use php config directives that cannot be overwritten: See this for details:

https://ma.ttias.be/php-php_value-vs-php_admin_value-and-the-use-of-php_flag-explained/

Can you show me your webserver config?

**Comment by stiang** [comment]
Thanks for the quick reply! I don’t think this is the reason - there are no `php_value/php_flag` instances in the entire repo. Here is the Dockerfile for Apache:

```
FROM httpd:latest
RUN echo "Include conf/site.conf" >> /usr/local/apache2/conf/httpd.conf
RUN sed -i 's/^#LoadModule proxy_http_module /LoadModule proxy_http_module /g' /usr/local/apache2/conf/httpd.conf
RUN sed -i 's/^#LoadModule proxy_module /LoadModule proxy_module /g' /usr/local/apache2/conf/httpd.conf
RUN sed -i 's/^#LoadModule proxy_fcgi_module /LoadModule proxy_fcgi_module /g' /usr/local/apache2/conf/httpd.conf
RUN sed -i 's/^#LoadModule rewrite_module /LoadModule rewrite_module /g' /usr/local/apache2/conf/httpd.conf
```

The vhost config is very standard, it just forwards requests for .php files to the PHP-FPM container:

```
    <FilesMatch \.php$>
        SetHandler "proxy:fcgi://php:9000"
    </FilesMatch>
```

The PHP-FPM container config (using docker-compose) is also pretty standard, it mostly just mounts some files/folders:

```
  php:
    build:
      context: ./support/docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/srv/www/html/current
      - ./support/srv-data:/srv/www/data
      - ./support/docker/php/ini:/etc/php-custom.d
      - ./support/docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    links:
      - mysql
```

So I’m really not sure why this won’t work. `phpinfo()` specifically lists the override file in the "Additional .ini files parsed" section. 

Can you confirm that you are able to *actually* override something using a custom php.ini, not just in theory?
